sudo: false
language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "5"
before_script:
  - npm prune
